#!/bin/bash
# Regenerate sway + waybar color files from the current pywal cache, then
# reload both. This is the sway equivalent of your old `update-dwm-colors`.
#
# Usage: update-sway-colors.sh [wallpaper-path]
#   wallpaper-path is optional — if omitted, falls back to whatever's in
#   ~/.cache/current-wallpaper, or to a solid color if neither is known.
#
# You can also run this by hand any time after a manual `wal -i <image>`.

set -uo pipefail

IMG="${1:-$(cat "$HOME/.cache/current-wallpaper" 2>/dev/null || true)}"
WAL_SHELL="$HOME/.cache/wal/colors.sh"
SWAY_COLORS="$HOME/.config/sway/colors"
WAYBAR_COLORS="$HOME/.config/waybar/colors.css"

if [[ ! -f "$WAL_SHELL" ]]; then
    echo "Error: wal colors not found. Run 'wal -i <image>' first." >&2
    exit 1
fi

# wal's colors.sh references $FZF_DEFAULT_OPTS without a default, which
# trips `set -u` if that var isn't already set. Relax nounset just for
# the source.
set +u
# shellcheck disable=SC1090
source "$WAL_SHELL"
set -u

mkdir -p "$(dirname "$SWAY_COLORS")" "$(dirname "$WAYBAR_COLORS")"

### sway ###
if [[ -n "$IMG" && -f "$IMG" ]]; then
    BG_LINE="output * bg \"$IMG\" fill"
else
    BG_LINE="output * bg $background solid_color"
fi

cat > "$SWAY_COLORS" << EOF
# Generated by update-sway-colors.sh — do not edit by hand.
# Included from your main sway config via: include ~/.config/sway/colors
#
# class                   border       background   text         indicator    child_border
client.focused            $color4      $color4      $background  $color4      $color4
client.focused_inactive   $color8      $background  $foreground  $color8      $color8
client.unfocused          $color8      $background  $foreground  $color8      $color8
client.urgent             $color1      $color1      $background  $color1      $color1

$BG_LINE
EOF

### waybar ###
cat > "$WAYBAR_COLORS" << EOF
/* Generated by update-sway-colors.sh — do not edit by hand.
   Imported from style.css via: @import url("colors.css"); */
@define-color bg       $background;
@define-color fg       $foreground;
@define-color accent   $color4;
@define-color muted    $color8;
@define-color urgent   $color1;
@define-color warning  $color3;
@define-color charging $color2;
@define-color select   $color7;
EOF

### reload ###
swaymsg reload >/dev/null 2>&1 || true

pkill -x waybar 2>/dev/null || true
sleep 0.1
setsid waybar >/dev/null 2>&1 &
disown

echo "sway + waybar colors updated."
